### ISSUE TITLE
Thread locked and waiting a Jdom2 parsing

### ISSUE THREAD

**Issue by davinkevin** [hunterhacker/jdom#142]
Hi, 

I use jDom to parse XML every hours (RSS form podcast) and I find some thread locked (RUNNING, but waiting indefinitely) while trying to parse an URL (seems to often happen, not every time, with http://www.season1.fr/category/Podcast/feed/).

```
"Update-3" Id=379 cpu=2623539166 ns usr=2530000000 ns blocked 19 for -1 ms waited 7 for -1 ms (running in native)
   java.lang.Thread.State: RUNNABLE
	locks java.util.concurrent.ThreadPoolExecutor$Worker@39ca5739
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:150)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked (a java.io.BufferedInputStream@751e0e75) index 4 frame java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
	- locked (a sun.net.www.http.ChunkedInputStream@2850d88f) index 6 frame sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3335)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2921)
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:302)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1743)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanData(XMLEntityScanner.java:1242)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanCDATASection(XMLDocumentFragmentScannerImpl.java:1654)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3020)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:277)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1141)
	at lan.dk.podcastserver.utils.jDomUtils.jdom2Parse(jDomUtils.java:54)
	at lan.dk.podcastserver.manager.worker.updater.RSSUpdater.getItems(RSSUpdater.java:42)
	at lan.dk.podcastserver.manager.worker.updater.AbstractUpdater.update(AbstractUpdater.java:34)
	at sun.reflect.GeneratedMethodAccessor332.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy268.update(Unknown Source)
	at lan.dk.podcastserver.business.UpdatePodcastBusiness.lambda$updateAsyncPodcast$11(UpdatePodcastBusiness.java:107)
	at lan.dk.podcastserver.business.UpdatePodcastBusiness$$Lambda$146/1783846520.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

This thread dump show the last call my application made was on the method "lan.dk.podcastserver.utils.jDomUtils.jdom2Parse(jDomUtils.java:54)". You can find this code at this url (https://github.com/davinkevin/Podcast-Server/blob/master/src/main/java/lan/dk/podcastserver/utils/jDomUtils.java#L54)

It seems no timeout was set on the reading of the streap, so the thread never finish / throw TimeOut...

Thanks for your help

Davin Kevin

**Comment by rolfl** [comment]
In this case it is clear that the SAX parser is waiting for data from the socket, and the socket is "stalled"... right? The actual locks you are concerned about are buried in the HTTP protocol handling (chunked).

In this case, JDOM2 is not causing any issue, it is the victim of the issue (data is not being supplied).

Note that JDOM is being given a URL, but SAX parsers expect an InputSource. This is a technicality that JDOM abstracts. The InputSource contains the URL in a string format. SAX then internally converts that string-form of the URL in to a URL connection, and reads the results.

While it is convenient in JDOM to pass the URL in to the build method, it is not possible for JDOM to set a timeout for that process.

URLConnections do support a timeout, but you have to set them before you create your connection.

In your calling code you do:

            url = new URL(urlasString);
            doc = sax.build(url);

You should change this to:

            url = new URL(urlasString);
            URLConnection urlCon = url.openConnection();
            urlCon.setReadTimeout(5000);
            doc = sax.build(urlCon.getInputStream(), urlasString);

This forces the URL connection to have the read timeout set, and you pass the actual INputStream to the parser, not the URL. The urlasString should also be passed in order to resolve any relative resources in the stream.

**Comment by davinkevin** [comment]
Thanks for your answer.
